# Generated by Django 3.1.3 on 2020-11-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='numero',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
